// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Server from "../Server.bs.js";
import * as FsExtra from "fs-extra";
import * as Playwright from "playwright";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function blub(prim0, prim1) {
  return FsExtra.outputFile(prim0, prim1);
}

function blah(prim) {
  return Caml_splice_call.spliceApply(Path.join, [prim]);
}

function meh(prim) {
  return Playwright.chromium();
}

var muh = Server.serve;

export {
  blub ,
  blah ,
  meh ,
  muh ,
  
}
/* path Not a pure module */
