// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Playwright from "playwright";

function launch(prim) {
  return Playwright.chromium.launch();
}

export {
  launch ,
  
}
/* playwright Not a pure module */
