// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";
import * as FsExtra from "fs-extra";

function copyDir(src, dest) {
  return $$Promise.$$catch(FsExtra.copy(src, dest).then(function (param) {
                  return Promise.resolve({
                              TAG: /* Ok */0,
                              _0: "ok"
                            });
                }), (function (e) {
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: e
                          });
              }));
}

function buildUrl(host, path, port) {
  return "" + host + ":" + port + path;
}

export {
  copyDir ,
  buildUrl ,
  
}
/* fs-extra Not a pure module */
