// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Minikin from "minikin";

function launch(prim) {
  return Minikin.default.default.server();
}

var respond = Minikin.Response;

export {
  launch ,
  respond ,
  
}
/* respond Not a pure module */
