// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Minikin from "minikin";

function serve(fn) {
  return Minikin.default.default.server().then(function (server) {
              var routes = fn(Minikin.Response.fromFile);
              return Promise.resolve((server.routes(routes), server));
            });
}

export {
  serve ,
  
}
/* minikin Not a pure module */
